# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fa8c3586944758ae39b7aaccee4a21b392d2c188eb5e28733014d8375038fbcf7db3614db351216d0112da046b2677afc59fc951aec3a6056d38f1a5a05ec50

test:
  secret_key_base: 609c6d0c0dd552270a11235400a42e20241fc1f7c767b93554b3fd8b2c258fe136ef2e31bb68f4fc04df9b542aeefd8a225a02bc535cf881701665db85735ddc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
